package probarTeclaA;

import componenteCaja.ArrastreListenerVertical;
import componenteCajonera.ArrastreListenerHorizontal;
import componentePulsador.PulsadorListener;
import componentePulsar.PulsacionListener;
import java.io.File;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Gonzalo
 */
public class ProbarTeclaA extends javax.swing.JFrame {

    /**
     * Creates new form ProbarTeclaA
     */
    public ProbarTeclaA() {
        initComponents();
        jPanelCaja1.addArrastreListenerVertical(new ArrastreListenerVertical() {
            @Override
            public void arrastre() {
                System.out.println("Se ha producido un gesto de arrastre" + new File("src/images/caja_abierta.png").getAbsolutePath());
                jPanelCaja1.setRutaImagen(new File("src/images/caja_abierta.png"));
            }
        });
        jPanelCajonera1.addArrastreListenerHorizontal(new ArrastreListenerHorizontal() {
            @Override
            public void arrastre() {
                System.out.println("Se ha producido un gesto de arrastre" + new File("src/images/cajonera_abierta.png").getAbsolutePath());
                jPanelCajonera1.setRutaImagen(new File("src/images/cajonera_abierta.png"));
            }
        });
        componentePulsar1.addPulsacionListener(new PulsacionListener(){
            @Override
            public void pulsacion() {
                
                System.out.println("Se ha pulsado la telca 'a'");
                //pulsador1.setRutaImagen(new File("src/images/pulsador_cerrado.png"));
            } 
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCaja1 = new componenteCaja.JPanelCaja();
        jPanelCajonera1 = new componenteCajonera.JPanelCajonera();
        jButtonReintentar = new javax.swing.JButton();
        pulsador1 = new componentePulsador.Pulsador();
        componentePulsar1 = new componentePulsar.ComponentePulsar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelCaja1.setRutaImagen(new java.io.File("C:\\Users\\gonza\\OneDrive\\Documentos\\NetBeansProjects\\ProbarTeclaA\\src\\images\\caja_cerrada.png"));

        javax.swing.GroupLayout jPanelCaja1Layout = new javax.swing.GroupLayout(jPanelCaja1);
        jPanelCaja1.setLayout(jPanelCaja1Layout);
        jPanelCaja1Layout.setHorizontalGroup(
            jPanelCaja1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 202, Short.MAX_VALUE)
        );
        jPanelCaja1Layout.setVerticalGroup(
            jPanelCaja1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        jPanelCajonera1.setRutaImagen(new java.io.File("C:\\Users\\gonza\\OneDrive\\Documentos\\NetBeansProjects\\ProbarTeclaA\\src\\images\\cajonera_cerrada.png"));

        javax.swing.GroupLayout jPanelCajonera1Layout = new javax.swing.GroupLayout(jPanelCajonera1);
        jPanelCajonera1.setLayout(jPanelCajonera1Layout);
        jPanelCajonera1Layout.setHorizontalGroup(
            jPanelCajonera1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 184, Short.MAX_VALUE)
        );
        jPanelCajonera1Layout.setVerticalGroup(
            jPanelCajonera1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 214, Short.MAX_VALUE)
        );

        jButtonReintentar.setText("REINTENTAR");
        jButtonReintentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReintentarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pulsador1Layout = new javax.swing.GroupLayout(pulsador1);
        pulsador1.setLayout(pulsador1Layout);
        pulsador1Layout.setHorizontalGroup(
            pulsador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 202, Short.MAX_VALUE)
        );
        pulsador1Layout.setVerticalGroup(
            pulsador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 194, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout componentePulsar1Layout = new javax.swing.GroupLayout(componentePulsar1);
        componentePulsar1.setLayout(componentePulsar1Layout);
        componentePulsar1Layout.setHorizontalGroup(
            componentePulsar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        componentePulsar1Layout.setVerticalGroup(
            componentePulsar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonReintentar, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelCaja1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(jPanelCajonera1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(pulsador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(274, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(componentePulsar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(202, 202, 202))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jButtonReintentar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelCajonera1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelCaja1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pulsador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(componentePulsar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonReintentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReintentarActionPerformed
        ProbarTeclaA frame = new ProbarTeclaA();
        this.dispose();
        frame.setVisible(true);
    }//GEN-LAST:event_jButtonReintentarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProbarTeclaA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProbarTeclaA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProbarTeclaA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProbarTeclaA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProbarTeclaA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private componentePulsar.ComponentePulsar componentePulsar1;
    private javax.swing.JButton jButtonReintentar;
    private componenteCaja.JPanelCaja jPanelCaja1;
    private componenteCajonera.JPanelCajonera jPanelCajonera1;
    private componentePulsador.Pulsador pulsador1;
    // End of variables declaration//GEN-END:variables

}
